apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  name: custom-distributedrediscluster
  namespace: redis-cluster
spec:
  image: registry.cn-shanghai.aliyuncs.com/taoistmonk/images:redis-5.0.13-alpine
  masterSize: 3
  clusterReplicas: 1
  serviceName: redis-svc
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi
  storage:
    type: persistent-claim
    size: 1Gi
    class: nfs-client
    deleteClaim: true
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: redis-cluster
spec:
  type: NodePort
  ports:
  - name: redis-6379
    port: 6379
    targetPort: 6379
    nodePort: 30071
  - name: redis-16379
    port: 16379
    targetPort: 16379
    nodePort: 30072

