apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  name: custom-distributedrediscluster
  namespace: redis-cluster
spec:
  image: redis:5.0.13-alpine
  masterSize: 3
  clusterReplicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi
  storage:
    type: persistent-claim
    size: 1Gi
    class: nfs-client
    deleteClaim: true