server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.177.18:3306/juneyao_new?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Admin@123,abc
  redis:
    host: 192.168.177.53
    port: 6379
    database: 1
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 1000
        max-wait: -1ms

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.juneyaoyun.dao: debug
juneyaoyun:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql